version: '3.8'
services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    depends_on:
      - db

  db:
    image: postgres
    # platform: linux/arm64 uncomment this line to run in macOS
    restart: always
    environment:
      POSTGRES_DB: gradeufop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d

volumes:
  db-data:
